#!/usr/bin/env ruby

require 'daemons'

RAILS_ROOT = File.expand_path('../..', __FILE__)
PID_DIR = File.expand_path('tmp/pids', RAILS_ROOT)

Dir.mkdir(PID_DIR) unless File.exists?(PID_DIR)

options = {
  dir_mode:   :script,
  dir:        PID_DIR,
  log_output: true,
  monitor:    true,
}

Daemons.run_proc('rails_server', options) do
  Dir.chdir(RAILS_ROOT)
  require File.join(RAILS_ROOT, 'config/environment')
  require 'rails/commands/server'

  # ignore whatever args are passed (causes issues with Server::Options)
  ARGV.clear

  # Rails::Server doesn't shutdown cleanly with TERM
  Signal.trap('TERM') { ::Process.kill('INT', Process.pid)}

  s = Rails::Server.new
  s.options[:Host] = AppConfig[:host]
  s.options[:Port] = AppConfig[:port]
  s.options[:daemonize] = false
  s.start
end
